sudo: required

services:
 - docker

language: bash

env:
  matrix:
  - DOCKER_ARCH=amd64
  - DOCKER_ARCH=arm64
  # - DOCKER_ARCH=arm <-ca-certicates hangs with qemu

script:
- ./build/travis_build.sh

jobs:
  include:

  - stage: Manifest
    script:
    - ./build/travis_manifest.sh
    env:
